language: php
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

services:
    - mysql

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=29

matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - composer self-update
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('pass') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ppass
  - sudo service mysql restart

install:
  - composer install
  - cp .env.dist .env
  - php bin/console doctrine:schem:update --force
  - ./bin/phpunit install

script:
  - ./bin/phpunit
  - ./bin/console lint:yaml config